# Generated by Django 5.2.3 on 2025-06-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tecnologias', models.CharField(max_length=20)),
                ('imagem', models.FilePathField(path='/img')),
            ],
        ),
    ]
